# Configuration for project tucan-plus-android, connector repository1

# Learn more about the Teamscale IDE Configuration File Format at
# <https://docs.teamscale.com/reference/teamscale-toml/>.

version = "1.0"

root = true

[server]
url = "https://teamscale.selfmade4u.de"

[project]
id = "tucan-plus-android"

